name: comitons_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  objectbox: ^2.4.0
  entity: ^3.0.2
  objectbox_generator: 2.4.0
  objectbox_flutter_libs: 2.4.0
  path_provider: ^2.1.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0


flutter:

  uses-material-design: true
#  generate: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoSans-SemiBold
      fonts:
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
    - family: NotoSans-Medium
      fonts:
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
    - family: NotoSans-Light
      fonts:
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300
    - family: NotoSansJP-Light
      fonts:
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300